Crafting = {
	Nos = {
		Header = Loc[Config.Lan]["crafting"].toolheader,
		Anims = { animDict = "mini@repair", anim = "fixing_a_ped",},
		Recipes = {
			
		}
	},
	Repairs = {
		Header = Loc[Config.Lan]["crafting"].repairheader,
		Anims = { animDict = "mini@repair", anim = "fixing_a_ped",},
		Recipes = {
			{ ["mechanic_tools"] = { ["iron"] = 2, },
				["amount"] = 1,
			},
			{ ["ducttape"] = { ["plastic"] = 1, },
				["amount"] = 3,
			},
			{ ["newoil"] = { ["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["sparkplugs"] = { ["metalscrap"] = 1, },
				["amount"] = 2,
			},
			{ ["carbattery"] = { ["metalscrap"] = 2, ["plastic"] = 3 },
				["amount"] = 1,
			},
			{ ["axleparts"] = { ["steel"] = 3, },
				["amount"] = 1,
			},
			{ ["sparetire"] = { ["rubber"] = 4, },
				["amount"] = 1,
			},
		},
	},
	Tools = {
		Header = Loc[Config.Lan]["crafting"].toolheader,
		Anims = { animDict = "mini@repair", anim = "fixing_a_ped",},
		Recipes = {
			{ ["toolbox"] = {
				["iron"] = 3,
				["steel"] = 1,
				["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["paintcan"] = { ["aluminum"] = 1, },
				["amount"] = 2,
			},

			{ ["tint_supplies"] = { ["plastic"] = 1, },
				["amount"] = 2,
			},
			{ ["underglow_controller"] = { ["iron"] = 1, },
				["amount"] = 1,
			},
			{ ["cleaningkit"] = { ["rubber"] = 1, },
				["amount"] = 1,
			},
		},
	},
	Perform = {
		Header = Loc[Config.Lan]["crafting"].performheader,
		Anims = { animDict = "mini@repair", anim = "fixing_a_ped",},
		Recipes = {
			{ ["turbo"] = { ["steel"] = 30, },
				["amount"] = 1,
			},
			{ ["engine1"] = { ["steel"] = 10, },
				["amount"] = 1,
			},
			{ ["engine2"] = { ["steel"] = 20, },
				["amount"] = 1,
			},
			{ ["engine3"] = { ["steel"] = 30, },
				["amount"] = 1,
			},
			{ ["engine4"] = { ["steel"] = 40, },
				["amount"] = 1,
			},
			{ ["transmission1"] = { ["steel"] = 10, },
				["amount"] = 1,
			},
			{ ["transmission2"] = { ["steel"] = 20, },
				["amount"] = 1,
			},
			{ ["transmission3"] = { ["steel"] = 30, },
				["amount"] = 1,
			},
			{ ["brakes1"] = { ["steel"] = 10, },
				["amount"] = 1,
			},
			{ ["brakes2"] = { ["steel"] = 20, },
				["amount"] = 1,
			},
			{ ["brakes3"] = { ["steel"] = 30, },
				["amount"] = 1,
			},
			{ ["suspension1"] = { ["steel"] = 10, },
				["amount"] = 1,
			},
			{ ["suspension2"] = { ["steel"] = 20, },
				["amount"] = 1,
			},
			{ ["suspension3"] = { ["steel"] = 30, },
				["amount"] = 1,
			},
			{ ["suspension4"] = { ["steel"] = 40, },
				["amount"] = 1,
			},
			{ ["suspension5"] = { ["steel"] = 50, },
				["amount"] = 1,
			},
			{ ["drifttires"] = { ["rubber"] = 100, },
				["amount"] = 1,
			},
			{ ["antilag"] = { ["steel"] = 1, },
				["amount"] = 1,
			},
		},
	},
	Cosmetic = {
		Header = Loc[Config.Lan]["crafting"].cosmetheader,
		Anims = { animDict = "mini@repair", anim = "fixing_a_ped",},
		Recipes = {
			{ ["hood"] = { ["plastic"] = 5, },
				["amount"] = 1,
			},
			{ ["roof"] = { ["plastic"] = 3, },
				["amount"] = 1,
			},
			{ ["spoiler"] = { ["plastic"] = 6, },
				["amount"] = 1,
			},
			{ ["bumper"] = { ["plastic"] = 4, },
				["amount"] = 1,
			},
			{ ["skirts"] = { ["plastic"] = 4, },
				["amount"] = 1,
			},
			{ ["exhaust"] = { ["iron"] = 2, },
				["amount"] = 1,
			},
			{ ["seat"] = { ["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["livery"] = { ["paintcan"] = 2 },
				["amount"] = 1,
			},
			{ ["tires"] = { ["rubber"] = 10, },
				["amount"] = 1,
			},
			{ ["horn"] = { ["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["internals"] = { ["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["externals"] = { ["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["customplate"] = { ["steel"] = 1, },
				["amount"] = 1,
			},
			{ ["headlights"] = { ["plastic"] = 1, },
				["amount"] = 1,
			},
			{ ["rims"] = { ["iron"] = 10, },
				["amount"] = 1,
			},
			{ ["rollcage"] = { ["steel"] = 6, },
				["amount"] = 1,
			},
		},
	},
}

Stores = {
	NosItems = {
		label = Loc[Config.Lan]["stores"].nos,
		items = {
			{ name = "nos", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "noscolour", price = 0, amount = 50, info = {}, type = "item", },
		},
	},
	RepairItems = {
		label = Loc[Config.Lan]["stores"].repairs,
		items = {
			{ name = "mechanic_tools", price = 0, amount = 10, info = {}, type = "item", },
			{ name = "sparetire", price = 0, amount = 100, info = {}, type = "item", },
			{ name = "axleparts", price = 0, amount = 1000, info = {}, type = "item", },
			{ name = "carbattery", price = 0, amount = 1000, info = {}, type = "item", },
			{ name = "sparkplugs", price = 0, amount = 1000, info = {}, type = "item", },
			{ name = "newoil", price = 0, amount = 1000, info = {}, type = "item", },
		},
	},
	ToolItems = {
		label = Loc[Config.Lan]["stores"].tools,
		items = {
			{ name = "toolbox", price = 0, amount = 10, info = {}, type = "item", },
			{ name = "ducttape", price = 0, amount = 100, info = {}, type = "item", },
			{ name = "paintcan", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "tint_supplies", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "underglow_controller", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "cleaningkit", price = 0, amount = 100, info = {}, type = "item", },
		},
	},
	PerformItems = {
		label = Loc[Config.Lan]["stores"].perform,
		items = {
			{ name = "turbo", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "engine1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "engine2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "engine3", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "engine4", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "engine5", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "transmission1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "transmission2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "transmission3", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "transmission4", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "brakes1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "brakes2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "brakes3", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "car_armor", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "suspension1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "suspension2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "suspension3", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "suspension4", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "suspension5", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "bprooftires", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "drifttires", price = 0, amount = 50, info = {}, type = "item", },

			{ name = "oilp1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "oilp2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "oilp3", price = 0, amount = 50, info = {}, type = "item", },

			{ name = "drives1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "drives2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "drives3", price = 0, amount = 50, info = {}, type = "item", },

			{ name = "cylind1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "cylind2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "cylind3", price = 0, amount = 50, info = {}, type = "item", },

			{ name = "cables1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "cables2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "cables3", price = 0, amount = 50, info = {}, type = "item", },

			{ name = "fueltank1", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "fueltank2", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "fueltank3", price = 0, amount = 50, info = {}, type = "item", },

			{ name = "harness", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "antilag", price = 0, amount = 50, info = {}, type = "item", },
		},
	},
	CosmeticItems = {
		label = Loc[Config.Lan]["stores"].cosmetic,
		items = {
			{ name = "hood", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "roof", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "spoiler", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "bumper", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "skirts", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "exhaust", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "seat", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "livery", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "tires", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "horn", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "internals", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "externals", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "customplate", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "headlights", price = 0, amount = 50, info = {}, type = "item", },
			{ name = "rims", price = 0, amount = 100, info = {}, type = "item", },
			{ name = "rollcage", price = 0, amount = 50, info = {}, type = "item", },
		},
	},
}

-- No Touch
	-- This is corrective code to help simplify the stores for people removing the slot info
	-- Jim shops doesn"t use it but other inventories do
	-- Most people don"t even edit the slots, these lines generate the slot info autoamtically
Stores.CosmeticItems.slots = #Stores.CosmeticItems.items
for k in pairs(Stores.CosmeticItems.items) do Stores.CosmeticItems.items[k].slot = k end
Stores.PerformItems.slots = #Stores.PerformItems.items
for k in pairs(Stores.PerformItems.items) do Stores.PerformItems.items[k].slot = k end
Stores.ToolItems.slots = #Stores.ToolItems.items
for k in pairs(Stores.ToolItems.items) do Stores.ToolItems.items[k].slot = k end
Stores.RepairItems.slots = #Stores.RepairItems.items
for k in pairs(Stores.RepairItems.items) do Stores.RepairItems.items[k].slot = k end
Stores.NosItems.slots = #Stores.NosItems.items
for k in pairs(Stores.NosItems.items) do Stores.NosItems.items[k].slot = k end